sudo: false
language: node_js
node_js:
  - "0.12"
cache:
  directories:
    - node_modules
env:
  global:
    # Sauce Labs are OK with this and it is currently necessary to expose this information for testing pull requests;
    # please get your own free key if you want to test yourself
    - SAUCE_USERNAME: dojo2-ts-ci
    - SAUCE_ACCESS_KEY: e92610e3-834e-4bec-a3b5-6f7b9d874601
    - BROWSERSTACK_USERNAME: dtktestaccount1
    - BROWSERSTACK_ACCESS_KEY: mG2qbEFJCZY2qLsM7yfx
  matrix:
    - NPM_SCRIPT: test-coverage
    - NPM_SCRIPT: test-remote-ci
script: "npm run $NPM_SCRIPT"
